### PR TITLE
Update runtime and app to latest versions

### PR DESCRIPTION
**Pull request by farribeiro**
Update runtime and app to latest versions

### CODE REVIEW

**Comment by farribeiro** [comment]
appstream file fails.

**Comment by PerryWerneck** [comment]
Updated on https://github.com/PerryWerneck/pw3270/commit/ef16611d8399115e5a35d2e728ff8cc1fdf694aa, needs testing.

**Comment by farribeiro** [comment]
You have to release a patched version so that it can be added to the pr

**Comment by farribeiro** [comment]
Ready to merge

**Pull request merged**
